baseURL: "https://thebrink.netlify.app" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
sitemap:
  changefreq: weekly
  priority: 0.8
title: The Brink
paginate: 5
theme: papermod
enableRobotsTXT: true
languageCode: "en-us"
canonifyURLs:true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
GoogleAnalyticsID: G-GQLDGQF9G6

minify:
  disableXML: true
  # minifyOutput: true

languageName: "English"
weight: 1
taxonomies:
category: categories
tag: tags
series: series
menu:
  main:
    # - name: Archive
      # url: archives
      # weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight:
        10
        #  - name: About Me
        # url: https://ar0177417.netlify.app

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  #laber.icon: logo.png
  env: production # to enable google analytics, opengraph, twitter-cards and schema. set to production
  title: "The Brink"
  description: "Website from a passionate blogger and a linux nerd"
  author: ar0177417
  keywords: ["tech","Brink","The Brink","Brink Blog","ardrag0n","ar0177417","Ahmad Rehan"]
  # author: ["Me", "You"] # multiple authors
  defaultTheme: auto
  # disableThemeToggle: true
  ShowFullTextinRSS: true
  ShowShareButtons: true
  disableShare: false
  ShowReadingTime: true
  # disableSpecial1stPost: true
  hidemeta: false
  comments: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  hideSummary: false
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  UseHugoToc: true
  ShowCodeCopyButtons: true
  # comments: false
  # images: ["papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hey There, \U0001F44B"
    Content: This website is my Journal for noting useful information and expressing my views.
  socialIcons:
    - name: github
      url: "https://github.com/ardrag0n"
    - name: Twitter
      url: "https://twitter.com/ar0177417"
    - name: Rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/ardrag0n/website/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  label:
    text: " "
    icon: /images/logo-light.webp
    iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: "JHws0ngpf3DJxJ4K89UzYkFlZP4btEK0bTn6U7QbYdY"

  assets:
    disableHLJS: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "apple-touch-icon.png"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
